services:
  contactlistservice:
    image: contactlistservice
    build:
      context: .
      dockerfile: ContactListService/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DbConnection=Host=db;Database=contacts;Username=postgres;Password=password

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=contacts
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d contacts" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

